export { FavoriteList } from "./FavoriteList/FavoriteList"
export { FilmIdPage } from "./FilmIdPage/FilmIdPage"
export { LoginPage } from "./LoginPage/LoginPage"
export { MoviesPage } from "./MoviesPage/MoviesPage"
export { NotFound } from "./NotFound/NotFound"
export { RegisterPage } from "./RegisterPage/RegisterPage"
export { SearchMovie } from "./SearchMoviePage/SearchMovie"
export { TrendMovie } from "./TrendMoviePage/TrendMovie"
